# Train or analyze performance
train_mode: 1
eval_mode: 0

# Dataset specs
nchannels: 3
img_size: 64 # height and width of images
latent_size: 100

# Train specs
batch_size: 512
num_epochs: 50
update_every: 1 # Update discriminator every __ batches
print_every: 1 # Print stats every __ batches
real_labels: 0.95
fake_labels: 0

# Optimizer
lr: 0.0002
beta1: 0.5

# GPU setup
gpu_type: 'nvidia' # mac, nvidia
multiple_gpus: True

# For saving samples
num_constant: 8

# Filenames for saved stuff
losses_fname: 'train_losses.npy' # Numpy array (epoch, 2) - gen, disc
samples_fname: 'train_samples.npy' # Numpy array (epoch, 4, nchannels, img_size, img_size)
acc_fname: 'train_accuracies.npy' # Numpy array (epoch, 2) - real, fake
av_preds_fname: 'av_preds.npy' # # Numpy array (epoch, 2) - real, fake

# Filenames for logging
log_fname: 'train_log' # Instead of print statement
log_extra_fname: 'train_extra' # Log loss, accuracy